;ANDRE MOREIRA TAVARES
#include "p16f628a.inc"
; CONFIG
; __config 0xFF7B
 __CONFIG _FOSC_INTOSCIO & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _BOREN_ON & _LVP_OFF & _CPD_OFF & _CP_OFF
;nomeando posições da memória RAM
CBLOCK 0X20
    FLAGS	;0x20
    UNIDADE	;0x22
    F_UP	;0x23
    F_DOWN	;0x24
 ENDC
 ;entradas
 #define    BOTAO_ZER		PORTA,1
 #define    BOTAO_INC	        PORTA,2
 #define    BOTAO_DEC		PORTA,3
 ;saidas
 #define    NUMERO		PORTB
 ;constantes
 #define    JA_UP		FLAGS,0
 #define    JA_DOWN		FLAGS,1
 ;filtros
 FILTRO	    equ			.50		
 ;========PROGRAMA==================
RES_VECT  CODE    0x0000            ; vetor de reset, indica a posição inicial do programa na FLASH
    BSF	    STATUS,RP0		    ;selecionando o banco 1 da memória RAM
    MOVLW   B'00000000'		    ;W= B'11110000'(.240)
    MOVWF   TRISB		    ;DEFININDO AS SAIDAS E ENTRADAS DO PORTB
    BCF	    STATUS,RP0		    ;seleciona o banco 0 da memória RAM
    CLRF    UNIDADE		    ;LIMPA FLAG DE MEMORIA UNIDADE
    BCF     JA_UP		    ;LIMPA BIT DE MEMORIA JA_UP
    BCF     JA_DOWN		    ;LIMPA BIT DE MEMORIA JA_DOWN
    CALL    ESCREVE_DISPLAY	    ;COMECA MOSTRANDO 0 NO DISPLAY
    

VERIFICAR_BOTAO_ZER
    BTFSS   BOTAO_ZER		    ;LE E TESTA O BOTAO DE ZERAR
    GOTO    ZERAR_PRESS		    ;SE PRESSIONADO VAI PARA ZERAR_PRESS(0)
VERIFICAR_BOTAO_INC			
    BTFSS   BOTAO_INC		    ;LE E TESTA O BOTAO DE INCREMENTO
    GOTO    INCREMENTAR		    ;SE PRESSIONADO VAI PARA INCREMENTAR(0)
    BCF     JA_UP		    ;CASO NAO FOI PRESSIONADO LIMPA JA_UP
    MOVLW   FILTRO		    
    MOVWF   F_UP		    ;E REINICIA O FILTRO
VERIFICAR_BOTAO_DEC
    BTFSS   BOTAO_DEC		    ;LE E TESTA O BOTAO DE DECREMENTO
    GOTO    DECREMENTAR		    ;VAI PARA DECREMENTAR CASO PRESSIONADO (0)
    BCF    JA_DOWN		    ;LIMPA JA_DOWN
    MOVLW   FILTRO	    
    MOVWF   F_DOWN		    ;REINICIA FILTRO
    GOTO    VERIFICAR_BOTAO_ZER	    ;VOLTA PARA O INICIO PARA MANTER O LOOP
    
    
INCREMENTAR
    BTFSC   JA_UP		    ;TESTA SE JA SUBIU
    GOTO    VERIFICAR_BOTAO_DEC	    ;SE SIM VOLTA PRO LOOP PRINCIPAL
    DECFSZ  F_UP,F		    ;CASO NAO DECREMENTA O FILTRO E SKIP SE FOR 0
    GOTO    VERIFICAR_BOTAO_DEC	    ;PARA EVITAR O DEBOUNCE, E AQUI VOLTA PARA O LOOP PRINCIPAL PARA MANTER PRIORIDADE DO BOTAO ZERAR
    BSF	    JA_UP		    ;SETA QUE JA INCREMENTOU
    INCF    UNIDADE,F		    ;INCREMENTA UNIDADE
    MOVLW   .10			    ;W=10
    SUBWF   UNIDADE,W		    ;SUBTRAI W DE UNIDADE ( R = UNIDADE - W)
    BTFSC   STATUS,C		    ;TESTA SE HOUVE CARRY ( GEROU NUMERO NEGATIVO)
    CLRF    UNIDADE		    ;SE SIM LIMPA UNIDADE (RESETA)
    MOVF    UNIDADE,W		    ;W=UNIDADE PARA CHAMAR FUNCAO
    CALL    ESCREVE_DISPLAY	    ;ESCREVE NO DISPLAY
    GOTO    VERIFICAR_BOTAO_DEC	    ;VOLTA PARA O LOOP CONTINUANDO O PROGRAMA
    
DECREMENTAR
    BTFSC   JA_DOWN
    GOTO    VERIFICAR_BOTAO_ZER
    DECFSZ  F_DOWN,F
    GOTO    VERIFICAR_BOTAO_ZER
    BSF	    JA_DOWN
    MOVLW   .1			     ;W = 1
    SUBWF   UNIDADE,W		    ;DECREMENTANDO 1 DE UNIDADE, MANUALMENTE(R = UNIDADE - W)
    BTFSC   STATUS,C		    ;TESTA SE HOUVE CARRY
    GOTO    DECREMENTA_UNIDADE	    ;SE FOR MAIOR QUE 0 MOSTRA O VALOR QUE TEM
    MOVLW   .9			    ;RESETANDO A UNIDADE COM 9
    MOVWF   UNIDADE
    GOTO    CONTINUA		    ;VAI PARA MOSTRAR2 PARA PULAR O PASSO ABAIXO
DECREMENTA_UNIDADE
    MOVWF   UNIDADE		    ;GUARDANDO O DECREMENTO EM UNIDADE
CONTINUA    
    MOVF    UNIDADE,W		    ;GUARDA VALOR DE UNIDADE EM W PARA CHAMAR O ESCREVE
    CALL    ESCREVE_DISPLAY	    ;ESCREVE NO DISPLAY
    GOTO    VERIFICAR_BOTAO_ZER	    ;VOLTA PARA O INICIO DO LOOP
       
ZERAR_PRESS
    CLRF    UNIDADE		    ;LIMPAR UNIDADE
    CLRF    W			    ;LIMPAR W, POR GARANTIA
    CALL    ESCREVE_DISPLAY	    ;CHAMA ESCREVE DISPLAY
    GOTO    VERIFICAR_BOTAO_ZER	    ;RETORNA AO LACO PRINCIPAL
    
ESCREVE_DISPLAY
    CALL    BUSCA_CODIGO	    ;CHAMA SUBROTINA PARA BUSCAR O CODIGO DE 7 SEGMENTOS
    MOVWF   NUMERO		    ;NUEMERO = W (CODIGO DE 7 SEGUIMENTOS)
    RETURN			    ;RETORNA DA CHAMADA DE SUBROTINA
    
BUSCA_CODIGO
    ADDWF   PCL,F
    RETLW   .254		    ;0
    RETLW   .56			    ;1
    RETLW   .221		    ;2
    RETLW   .125		    ;3
    RETLW   .59			    ;4
    RETLW   .119		    ;5
    RETLW   .247		    ;6
    RETLW   .60			    ;7
    RETLW   .255		    ;8
    RETLW   .127		    ;9
    
    
    END
