
#include "p16f628a.inc"

; CONFIG
; __config 0xFF70
__CONFIG _FOSC_INTOSCIO & _WDTE_OFF & _PWRTE_ON & _MCLRE_ON & _BOREN_ON & _LVP_OFF & _CPD_OFF & _CP_OFF


RES_VECT CODE 0x0000 ; VETOR DE RESET, INDICA A POSI??O INICIAL DO PROGRAMA NA FLASH
    BSF STATUS,RP0 ; SELECIONA O BANCO I DA MEMORIA RAM
    BCF TRISA,0	; SAIDA A
    BCF TRISB,0 ; CONFIGURA O PINO 0 DA PORTA COMO SAIDA
    BCF TRISB,1 ; CONFIGURA O PINO 1 DA PORTA COMO SAIDA 
    BCF TRISB,2 ; CONFIGURA O PINO 2 DA PORTA COMO SAIDA
    BCF TRISB,3 ; CONFIGURA O PINO 3 DA PORTA COMO SAIDA
    BCF STATUS,RP0 ; VOLTA AO BANCO 0 DA MEMORIA RAM
    BCF PORTA,0 ; APAGA A LAMPADA
    BCF	PORTB,0 ; APAGA A LAMPADA
    BCF	PORTB,1 ; APAGA A LAMPADA
    BSF	PORTB,2 ; APAGA A LAMPADA
    BCF	PORTB,3 ; APAGA LAMPADA

ETAPA1
    BTFSC PORTA,3 ;LE E TESTA O BIT DA PORTA RA3 
    GOTO ETAPA3	;SE FALSE
    GOTO ETAPA2 ;SE TRUE
    
ETAPA2
    BCF PORTA,0
    BCF PORTB,0
    BCF PORTB,1
    BSF PORTB,2
    GOTO ETAPA1
    
ETAPA3
    BTFSC PORTA,4 ;LE E TESTA O BIT DA PORTA RA3 
    GOTO HORARIO_PRESS	;SE FALSE
    GOTO ETAPA4 ;SE TRUE
    
HORARIO_PRESS
    BTFSC PORTA,1 ;HORARIO FOI PRESSIONADO?
    GOTO ANTIHOR_PRESS ;SE NAO, VAI PRA CA
    GOTO ETAPA5 ;SE SIM VAI PRA ETAPA5

ANTIHOR_PRESS
    BTFSC PORTA,2 ;ANTIHORARIO FOI PRESSIONADO?
    GOTO ETAPA1 ;SE NAO, VOLTA PRA ETAPA 1
    GOTO ETAPA6 ;SE SIM VAI PRA ETAPA6


ETAPA4
    BCF PORTA,0
    BCF PORTB,0
    BCF PORTB,1
    BSF PORTB,2
    BSF PORTB,3
    BTFSC PORTA,3 ;BOTAO DESLIGA FOI PRESSIONADO?
    GOTO ETAPA4 ;SE NAO FOI VOLTA PRA ETAPA 4
    BCF PORTB,3 ;SE SIM DESLIGA MOTOR
    GOTO ETAPA1
  
ETAPA5
    BTFSC PORTB,1   ;ANTIHORARIO TA COMO ?
    GOTO ETAPA1 ;SE =1 VOLTA PRA ETAPA 1
    BSF PORTA,0 ;SE =0 CONTINUA
    BSF PORTB,0
    BCF PORTB,2
    GOTO ETAPA1
    
ETAPA6
    BTFSC PORTB,0
    GOTO ETAPA1 ;SE FOR 1 VOLTA PRA PRIMEIRA ETAPA
    BSF PORTA,0 ;SE FOR 0 CONTINUA
    BSF PORTB,1
    BCF PORTB,2
    GOTO ETAPA1
    
END